CREATE TABLE app_user (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) NOT NULL UNIQUE,
    password varchar(255) NOT NULL
);

CREATE TABLE recipe (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar(255),
    calories integer,
    price    numeric(38,2),
    owner_id bigint REFERENCES app_user (id)
);

CREATE TABLE recipe_ingredients (
    recipe_id     bigint  NOT NULL REFERENCES recipe (id),
    ingredient_no integer NOT NULL,
    name          varchar(255),
    amount        numeric(38,2),
    unit          varchar(255),
    price         numeric(38,2),
    PRIMARY KEY (recipe_id, ingredient_no)
);

CREATE TABLE recipe_instructions (
    recipe_id    bigint  NOT NULL REFERENCES recipe (id),
    step_no      integer NOT NULL,
    instructions varchar(255),
    PRIMARY KEY (recipe_id, step_no)
);